Repository gitpod-io/website, pull requests merged in 2020-12, with the labels that each got.

#851 Add feature preview docs and a note about custom IDE images
  src/docs/feature-preview.md
  src/docs/menu.ts
Labels: blocked, documentation

#875 Fix links on Languages & Frameworks
  src/docs/languages-and-frameworks.md
  src/docs/menu.ts
Labels: community contribution, documentation

#862 Update header navigation
  src/components/Nav.tsx
Labels: navigation

#880 Update Intro Section of Documentation
  src/docs/images/gitpod-architecture.png
  src/docs/index.md
Labels: documentation

#879 Improve Getting Started section in the docs
  src/docs/context-urls.md
  src/docs/getting-started.md
Labels: documentation

#891 Adjusted blog post for Univers w. context/links/ bold text
  src/blog/moving-software-development-to-the-cloud.md
Labels: blog

#898 [docs] Added Next Steps section
  src/docs/getting-started.md
  src/docs/index.md
Labels: documentation
