Repository gitpod-io/website, pull requests merged in 2021-03, with the labels that each got.

#1003 docs: split prebuild instructions on a per hosting platform basis
  src/docs/prebuilds.md
Labels: documentation

#1015 Change the wording in SubmissionSuccess.tsx
  src/components/SubmissionSucess.tsx
Labels: community contribution

#1023 security: move security.txt to website from gitpod-io/gitpod
  .github/ISSUE_TEMPLATE/config.yml
  SECURITY.md
  netlify.toml
  static/.well-known/security.txt
Labels: documentation, enhancement, user experience

#1020 docs: clarification that the MSFT debugger is proprietary
  src/docs/languages/dotnet.md
Labels: documentation

#1025 careers: gatsby is being retired
  src/pages/careers.tsx
Labels: career

#508 [docs] Elm in Gitpod
  src/docs/images/ElmExtensionDemo.png
  src/docs/languages-and-frameworks.md
  src/docs/languages/elm.md
  src/docs/menu.ts
Labels: documentation

#1022 docs: associate flutter with dart to improve discoverability
  src/docs/languages-and-frameworks.md
  src/docs/menu.ts
Labels: documentation

#1026 careers: add Senior Developer Success Engineer
  src/pages/careers.tsx
Labels: career

#1031 docs: add reference to dotnet lts images
  src/docs/languages/dotnet.md
Labels: documentation
