Repository gitpod-io/website, pull requests merged in 2021-02, with the labels that each got.

#911 Add getting started button
  src/components/index/Banner.tsx
Labels: navigation

#1002 Fix typo in docs
  src/docs/github-integration.md
Labels: community contribution, documentation

#1001 [docs] fix: grammatical error
  src/docs/config-start-tasks.md
Labels: community contribution, documentation

#985 Refresh contact subjects & links
  src/blog/gitlab-support.md
  src/components/pricing/PricingFAQs.tsx
  src/contents/enterprise.tsx
  src/docs/release-notes/2019-04-05/april-2019.md
  src/pages/contact.tsx
  src/pages/education.tsx
  src/pages/enterprise-license.tsx
  src/pages/enterprise.tsx
  src/pages/recruiting.tsx
  src/pages/self-hosted.tsx
  src/pages/vendor.tsx
  static/release-notes/2019-04-05/april-2019.md
Labels: SEO, career, documentation, navigation

#904 Add link to Drupal starterkit.
  src/docs/languages/php.md
Labels: community contribution

#669 docs(LaTeX): use texlive instead of texlive-full
  src/docs/languages/latex.md
Labels: community contribution, documentation
