Repository gitpod-io/website, pull requests merged in 2021-08, with the labels that each got.

#807 docs(selfhosted): add helm repo update command
  src/routes/docs/self-hosted/latest/installation/on-kubernetes.md
Labels: documentation

#812 fix(changelog): single source of truth
  netlify.toml
  src/routes/docs/changelog.md
  src/routes/docs/menu.ts
  src/routes/docs/references/changelog.md
  src/routes/docs/references/index.md
Labels: documentation, a11y

#819 Add DevX Digest 1 onto the website
  src/assets/scss/_blog_preview.scss
  src/components/blog/blog-content-layout.svelte
  src/components/blog/digest-header.svelte
  src/components/blog/post-preview.svelte
  src/components/docs/feedback-widget.svelte
  src/components/post-content-layout.svelte
  src/components/twitter-follow-button.svelte
  src/contents/authors.ts
  src/functions/feedback/_manual.ts
  src/functions/feedback/index.ts
  src/routes/blog/the-evolution-of-devx.md
  src/routes/changelog/index.svelte
  src/utils/helper.ts
  static/images/blog/the-evolution-of-devx/evolution-of-devx.jpg
  static/images/blog/the-evolution-of-devx/source.png
  tailwind.config.cjs
Labels: in progress, blog

#824 docs(bookmarklet): an alternative to using the extension
  src/routes/blog/bitbucket.md
  src/routes/docs/browser-bookmarklet.md
  src/routes/docs/integrations/index.md
  src/routes/docs/menu.ts
  src/routes/docs/quickstart/datasette.md
  src/routes/docs/quickstart/deno.md
  src/routes/docs/quickstart/drupal.md
  src/routes/docs/quickstart/flask.md
  src/routes/docs/quickstart/go.md
  src/routes/docs/quickstart/haskell.md
  src/routes/docs/quickstart/index.md
  src/routes/docs/quickstart/java.md
  src/routes/docs/quickstart/laravel.md
  src/routes/docs/quickstart/nix.md
  src/routes/docs/quickstart/python.md
  src/routes/docs/quickstart/react.md
  src/routes/docs/quickstart/ruby-on-rails.md
  src/routes/docs/quickstart/rust.md
  src/routes/docs/quickstart/svelte.md
  src/routes/docs/quickstart/typescript.md
  src/routes/extension-uninstall.svelte
  static/images/docs/browser-bookmarklet-edit.png
  static/images/docs/browser-bookmarklet.png
Labels: documentation

#825 docs(quickstart): add more quickstart templates
  src/routes/docs/menu.ts
  src/routes/docs/quickstart/c.md
  src/routes/docs/quickstart/index.md
  src/routes/docs/quickstart/julia.md
  src/routes/docs/quickstart/perl.md
Labels: documentation

#853 Fix screencast numbering
  src/contents/screencasts.ts
Labels: bug

#864 Update docs to include screencasts
  src/routes/docs/config-gitpod-file.md
  src/routes/docs/getting-started.md
  src/routes/docs/prebuilds.md
  src/routes/docs/sharing-and-collaboration.md
  src/routes/docs/vscode-extensions.md
  src/routes/docs/workspaces.md
Labels: documentation

#880 Fix collaboration with your team link
  src/contents/screencasts.ts
  src/routes/screencasts/[title].svelte
Labels: bug

#856 Fix permalink color issue on the Careers page
  src/routes/careers.svelte
Labels: community-contribution
