Repository gitpod-io/website, pull requests merged in 2021-12, with the labels that each got.

#1286 Fixed overflow on last blog post.
  src/components/blog/post-preview.svelte
Labels: community-contribution

#1259 Add PlanetScale quickstart guide
  src/routes/docs/quickstart/planetscale.md
  src/stores/quickstarts.ts
Labels: community-contribution

#1219 Docs update for contribution with Gitpod.
  src/routes/docs/contribute/features-and-patches/submitting-a-pull-request.md
Labels: community-contribution

#1359 Document IDE usage via VNC
  src/routes/docs/editors/index.md
Labels: community-contribution

#1370 fix simple typo
  src/routes/blog/local-services-in-gitpod.md
Labels: community-contribution

#1358 Improve `remarkHeadingsPermalinks`
  src/routes/blog/ephemeral-dev-envs.md
  src/routes/blog/prebuilds.md
  src/routes/docs/editors/index.md
  src/routes/docs/environment-variables.md
  src/routes/docs/references/gitpod-yml.md
  src/utils/remark-headings-permalinks.js
Labels: documentation, community-contribution

#1338 Improve docs for prebuilds and custom Dockerfiles
  src/routes/docs/prebuilds.md
Labels: section: docs

#1218 Clarify self-hosted plans
  src/contents/self-hosted.ts
  src/routes/enterprise-license.svelte
Labels: section: docs

#1296 Add page-level ToC on docs
  package-lock.json
  package.json
  src/assets/markdown-commons.scss
  src/assets/scss/_blog_preview.scss
  src/assets/scss/_reset.scss
  src/components/docs/docs-content-layout.svelte
  src/components/docs/menu.svelte
  src/components/on-this-page-nav.svelte
  src/components/post-content-layout.svelte
  src/routes/changelog/[slug].svelte
  src/routes/changelog/index.svelte
  src/routes/docs/__layout.svelte
  src/routes/docs/languages/dotnet.md
  src/routes/docs/languages/rust.md
  svelte.config.js
  tailwind.config.cjs
Labels: section: docs

#1400 Typos in 'Start Tasks' doc
  gitpod/docs/config-start-tasks.md
Labels: community-contribution

#1399 fix / [about]: images are not aligned properly. #1395
  src/lib/assets/scss/_images-across.scss
Labels: community-contribution

#1406 index/section-ides: correct Browser/Desktop label
  src/lib/components/index/section-ides.svelte
Labels: community-contribution
