Repository gitpod-io/website, pull requests merged in 2021-11, with the labels that each got.

#1193 typo fix 🙂
  src/functions/feedback/index.ts
Labels: community-contribution

#1224 vscode.extensions exam should use correct example.
  src/routes/docs/references/gitpod-yml.md
Labels: community-contribution

#1231 [DevX Digest] Psychology of DevX
  src/contents/authors.ts
  src/routes/blog/psychology-of-devx.md
  static/images/blog/psychology-of-devx/teaser.png
Labels: blog

#1223 fix: update wording for workspace deletion
  src/routes/docs/life-of-workspace.md
Labels: team: IDE

#1261 Added operations manager position
  src/contents/careers.ts
Labels: awaiting-response
