Repository gitpod-io/website, pull requests merged in 2022-04, with the labels that each got.

#1866 Update config-ports.md
  gitpod/docs/config-ports.md
Labels: community-contribution

#1971 Updated description of self hosted cluster guides
  gitpod/docs/self-hosted/latest/cluster-set-up/index.md
  gitpod/docs/self-hosted/latest/cluster-set-up/on-amazon-eks.md
  gitpod/docs/self-hosted/latest/cluster-set-up/on-gke.md
  gitpod/docs/self-hosted/latest/cluster-set-up/on-microsoft-aks.md
Labels: section: docs

#1885 feat: add external collaboration tool links
  gitpod/docs/sharing-and-collaboration.md
Labels: team: IDE
