Repository gitpod-io/website, pull requests merged in 2022-11, with the labels that each got.

#2995 Document default billing account for usage-based billing
  gitpod/docs/configure/billing/usage-based-billing.md
  static/images/docs/billing/select-default-billing-account.png
Labels: team: webapp

#3006 feat: support Go & TS in code lang highlights
  src/lib/utils/highlight.js
Labels: team: website

#3013 docs: add rider and cliond docs
  generators/ide/jb-gen.js
  generators/ide/jb-product.md
  gitpod/docs/configure/self-hosted/latest/backup-restore.md
  gitpod/docs/references/ides-and-editors/clion.md
  gitpod/docs/references/ides-and-editors/index.md
  gitpod/docs/references/ides-and-editors/rider.md
  package-lock.json
  package.json
  src/lib/components/customers/customers-content-layout.svelte
  src/lib/components/post-content-layout.svelte
  src/lib/components/youtube-embed.svelte
  src/lib/contents/docs/menu.ts
  src/routes/privacy.svelte
Labels: team: IDE, editor: jetbrains
