Repository gitpod-io/website, pull requests merged in 2022-08, with the labels that each got.

#2555 feat: add C# .NET template to quickstart page
  gitpod/docs/quickstart/dotnet.md
  src/lib/stores/quickstarts.ts
Labels: section: quickstarts, docs-enhancement

#2388 Add Proof-of-Value Reference Architecture
  gitpod/docs/self-hosted/latest/reference-architecture/index.md
  gitpod/docs/self-hosted/latest/reference-architecture/proof-of-value.md
Labels: team: self-hosted

#2589 nit: updated assets for env. vars page
  static/images/docs/beta/configure/environment-variables/environment-variables-account-settings.png
Labels: enhancement

#2584 docs: example code snippet of open in gitpod button & badge
  gitpod/docs/getting-started.md
Labels: docs-enhancement

#2588 Add Guide: The Ultimate Guide to Ephemeral Dev Environment on Gitpod
  src/routes/guides/guide-ephemeral-dev-environment-on-gitpod/index.md
  static/images/guides/guide-ephemeral-dev-environment-on-gitpod/env-vars.png
  static/images/guides/guide-ephemeral-dev-environment-on-gitpod/gitpod-prebuilds.png
  static/images/guides/guide-ephemeral-dev-environment-on-gitpod/header.jpg
  static/images/guides/guide-ephemeral-dev-environment-on-gitpod/scope.png
  static/images/guides/guide-ephemeral-dev-environment-on-gitpod/teaser.jpg
  static/images/guides/guide-ephemeral-dev-environment-on-gitpod/tweet-image.png
Labels: section: guides

#2585 Lucas/pov ref arch description edits
  gitpod/docs/self-hosted/latest/reference-architecture/proof-of-value.md
Labels: on:hold, do not merge

#2624 Update Single Cluster Ref Arch AWS Workspace Node Storage to max throughput and IOPS
  gitpod/docs/self-hosted/latest/reference-architecture/_chunks/cluster.md
  gitpod/docs/self-hosted/latest/reference-architecture/single-cluster-ref-arch.md
Labels: do not merge

#2626 Revert "Update Single Cluster Ref Arch AWS Workspace Node Storage to max throughput and IOPS"
  gitpod/docs/self-hosted/latest/reference-architecture/_chunks/cluster.md
  gitpod/docs/self-hosted/latest/reference-architecture/single-cluster-ref-arch.md
Labels: on:hold

#2581 Removal of the limitation on immutable labels in self-hosted customization
  gitpod/docs/self-hosted/latest/advanced/customization.md
Labels: on:hold, do not merge

#2566 Update the backup/restore section with KOTS/Velero backup service
  gitpod/docs/self-hosted/latest/backup-restore.md
Labels: on:hold, do not merge

#2642 Fix focused Dashboard and Login buttons
  src/lib/components/ui-library/link-button/link-button.svelte
Labels: bug

#2381 add secondary cta to contact sales on the landing page + add the new design for the stars widget.
  .gitignore
  gitpod/docs/config-dotfiles.md
  gitpod/docs/self-hosted/latest/reference-architecture/proof-of-value.md
  package-lock.json
  package.json
  src/lib/components/explore.svelte
  src/lib/components/index/hero.svelte
  src/lib/components/index/section-ides.svelte
  src/lib/components/jetbrains-space/hero.svelte
  src/lib/components/layout-main.svelte
  src/lib/components/main-nav/github-stars.svelte
  src/lib/components/main-nav/index.svelte
  src/lib/components/main-nav/mobile-menu/index.svelte
  src/lib/components/main-nav/mobile-menu/toggle.svelte
  src/lib/components/main-nav/nav-item.svelte
  src/lib/components/main-nav/sign-up-button-tablet.svelte
  src/lib/components/svgs/octocat.svelte
  src/lib/contents/github-page.ts
  src/lib/contents/pricing.ts
  src/routes/__layout.svelte
  src/routes/api/banner.ts
  src/routes/api/layout.ts
  src/routes/vs/jetbrains-space.svelte
Labels: on:hold, do not merge

#2654 fix: code blocks styling
  src/lib/assets/markdown-commons.scss
Labels: enhancement

#2667 add redirects to fix 404 custom page error
  _redirects
  src/lib/components/404-error-page.svelte
  src/routes/404.svelte
  src/routes/sitemap.xml.ts
Labels: bug-fix

#2639 docs(gp-cli): document gp tasks stop cmd
  gitpod/docs/command-line-interface.md
Labels: team: IDE
