Repository gitpod-io/website, pull requests merged in 2022-12, with the labels that each got.

#3041 feat: Introduce Cypress test on each PR
  .github/workflows/cypress-e2e-test.yml
  .gitpod.yml
  cypress.json
Labels: Not Urgent - idea or suggestion

#3044 November Changelog
  gitpod/docs/configure/authentication/bitbucket.md
  gitpod/docs/configure/authentication/gitlab.md
  gitpod/docs/configure/projects/index.md
  gitpod/docs/configure/projects/prebuilds.md
  gitpod/docs/references/ides-and-editors/vscode-extensions.md
  src/lib/contents/changelog/2022-11-30.md
  static/images/changelog/2022-11-30-og.jpg
  static/images/jetbrains-gateway/jetbrains-ports-view.png
  static/images/jetbrains-gateway/port-actions-jetbrains-terminal.png
Labels: section: changelog

#3090 Migration to Cypress 11
  cypress.config.ts
  cypress.json
  cypress/e2e/enterprise_license_spec.cy.js
  cypress/e2e/sales_spec.cy.js
  cypress/e2e/support_spec.cy.js
  cypress/plugins/index.cjs
  package-lock.json
  package.json
Labels: team: website

#3093 Document the workspace-class preference in project setttings
  gitpod/docs/configure/projects/index.md
  gitpod/docs/configure/workspaces/workspace-classes.md
  static/images/docs/project-settings.png
  static/images/docs/select-workspace-class.png
Labels: team: webapp

#3103 Document that old plans first need to be cancelled to access pay-as-you-go
  gitpod/docs/configure/billing/pay-as-you-go.md
  static/images/docs/billing/configure-personal-billing.png
  static/images/docs/billing/configure-team-billing.png
Labels: team: webapp

#3081 Add documentation for personal access tokens
  gitpod/docs/configure/index.md
  gitpod/docs/configure/user-settings/access-tokens.md
  gitpod/docs/configure/user-settings/index.md
  src/lib/contents/docs/menu.ts
  static/images/docs/access-token-create.png
  static/images/docs/access-token-list.png
Labels: team: webapp

#2965 Refine JavaScript Language Page
  gitpod/docs/introduction/languages/javascript.md
Labels: team: website, docs-sub-section: learn gitpod, Urgent - essential to quarter goal

#2939 Gitpod public API docs
  gitpod/docs/configure/user-settings/access-tokens.md
  gitpod/docs/references/gitpod-public-api.md
  src/lib/contents/docs/menu.ts
Labels: Urgent - essential to quarter goal

#3200 seo: meta description
  src/routes/index.svelte
Labels: type: seo

#3060 Refine Go Language Page
  gitpod/docs/introduction/languages/go.md
  static/images/docs/goland-debug.webp
Labels: team: website, docs-sub-section: learn gitpod, Urgent - essential to quarter goal
