Repository gitpod-io/website, pull requests merged in 2023-02, with the labels that each got.

#3344 add kumquat logo in feature-title component
  src/lib/components/feature-title.svelte
  src/lib/components/feature-titles.svelte
  src/lib/types/feature-title.d.ts
  src/routes/about/team.svelte
Labels: community-contribution

#3343 Fix: Minor css change for RSS subscribe button
  src/lib/components/ui-library/subscribe-rss-feed.svelte
Labels: community-contribution, CLA: Signed

#3248 January Changelog
  package.json
  src/lib/contents/changelog/2023-01-31.md
  src/routes/changelog/index.svelte
  static/images/changelog/2023-01-31-og.jpg
  static/images/changelog/2023-01-31-prebuild-class.png
  static/images/changelog/2023-01-31.webp
  static/images/docs/new-workspace-start-with-options.webm
Labels: section: changelog

#3385 add meet-up guidelines to /community
  src/lib/components/community/callout-boxes.svelte
  static/images/community/meet-up.webp
Labels: community-contribution

#3368 Fixes scrollbar CSS for <pre> tag
  src/lib/assets/global.css
Labels: community-contribution, CLA: Signed

#3455 :wrench: Change CTA of Contact button
  src/lib/components/contact-widget.svelte
  src/lib/components/homepage-resources.svelte
  src/lib/components/index/hero.svelte
  src/lib/components/main-nav/demo-button.svelte
  src/lib/components/pricing/calculator/display-result.svelte
  src/lib/contents/contact.ts
  src/lib/contents/enterprise.ts
  src/lib/contents/pricing.ts
  src/routes/contact/sales.svelte
  src/routes/customers/index.svelte
  src/routes/for/enterprise.svelte
  src/routes/pricing.svelte
  src/routes/screencasts/demo.svelte
Labels: do not merge/hold
