Repository gitpod-io/website, pull requests merged in 2023-01, with the labels that each got.

#3214 Align beneift emojis consistently
  src/lib/components/careers/what-we-offer.svelte
Labels: team: website, CLA: Signed, type: design polish

#3196 Requests & Responses examples for Public API
  gitpod/docs/references/gitpod-public-api.md
  src/lib/components/docs/api-example.svelte
  src/lib/components/docs/cloud-platform-toggle.svelte
Labels: docs-sub-section: public api

#2786 Remember the last accessed tab in `<Ide-toggle>`
  src/lib/components/docs/ide-toggle.svelte
  src/lib/constants.ts
Labels: ux, section: docs-content

#3308 :bug: fix: UI Bug for pricing calculator slider
  src/lib/components/ui-library/range.svelte
Labels: type: bug

#3331 add description tag in docs layout
  src/lib/components/docs/docs-content-layout.svelte
Labels: CLA: Signed
